version: '3.8'

services:
  app:
    build: .
    
    container_name: asksuite_app
    
    ports:
      - "8080:8080"
      
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
    environment:
      - NODE_ENV=development
      - PORT=8080
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium